apiVersion: kueue.x-k8s.io/v1beta2
kind: WorkloadPriorityClass
metadata:
  name: wp-high
value: 1000
description: "High priority demo workloads"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: WorkloadPriorityClass
metadata:
  name: wp-low
value: 100
description: "Low priority demo workloads"
