apiVersion: v1
kind: Namespace
metadata:
  name: tas
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: tas-cluster-queue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["cpu", "nvidia.com/gpu"]
      flavors:
        - name: tas-gpu-flavor
          resources:
            - name: cpu
              nominalQuota: "100"
            - name: nvidia.com/gpu
              nominalQuota: "64"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  namespace: tas
  name: tas-local-queue
spec:
  clusterQueue: tas-cluster-queue
